### PR TITLE
Automated update of the homebrew tap - Tuneful (`Casks/tuneful.rb`)

### PR DESCRIPTION
**Pull request by rennaMAhcuS**
This workflow will check and update the **Tuneful** tap - **`Casks/tuneful.rb`** **once every day** (as long as both the repos are public 😉). This would be very useful for people like me, who rely on homebrew to update all their formulae and Casks.

**Fixes** #1

### CODE REVIEW

**Comment by rennaMAhcuS** [comment]
Looks like there's a small bug.

**Comment by rennaMAhcuS** [comment]
Yeah worked that out!

**Comment by martinfekete10** [comment]
This is amazing! I had something like this in mind but I'm not that skilled in devops 😄 Thank you!

**Comment by rennaMAhcuS** [comment]
There is a minor change to be done in the **`Casks/tuneful.rb`**: Just change
```rb
url "https://github.com/martinfekete10/Tuneful/releases/download/v#{version}/Tuneful.dmg"
```
to
```rb
url "https://github.com/martinfekete10/Tuneful/releases/download/#{version}/Tuneful.dmg"
```

**Comment by martinfekete10** [comment]
Done, thanks

**Pull request merged**
